-- Task 115: additional LeadFileType categories + FollowUpTask attachments
ALTER TYPE "LeadFileType" ADD VALUE IF NOT EXISTS 'FINAL_PITCH_PRESENTATION';
ALTER TYPE "LeadFileType" ADD VALUE IF NOT EXISTS 'PP_QUOTATION';
ALTER TYPE "LeadFileType" ADD VALUE IF NOT EXISTS 'PR_QUOTATION';
ALTER TYPE "LeadFileType" ADD VALUE IF NOT EXISTS 'PR_PRESENTATION';

ALTER TABLE "follow_up_tasks" ADD COLUMN IF NOT EXISTS "attachments" JSONB;
